# Generated by Django 2.0.6 on 2020-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100000)),
                ('box1', models.ImageField(upload_to='')),
                ('highs1', models.ImageField(upload_to='')),
                ('highs2', models.ImageField(upload_to='')),
                ('highs3', models.ImageField(upload_to='')),
                ('highs4', models.ImageField(upload_to='')),
                ('nav1', models.ImageField(upload_to='')),
                ('nav2', models.ImageField(upload_to='')),
                ('nav3', models.ImageField(upload_to='')),
                ('nav4', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
    ]
