# Generated by Django 2.0.6 on 2020-03-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedestinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='box2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='destination',
            name='box1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
