# Generated by Django 2.0.6 on 2020-03-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedestinations', '0002_auto_20200326_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc1',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='desc2',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highs_desc1',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highs_desc2',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highs_desc3',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highs_desc4',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highs_head1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highs_head2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highs_head3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='highs_head4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
