# Generated by Django 2.0.6 on 2020-03-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedestinations', '0005_auto_20200326_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='background',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='box1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='box2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='highs1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='highs2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='highs3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='highs4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nav1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nav2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nav3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nav4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
