# Generated by Django 2.0.6 on 2020-03-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedestinations', '0006_auto_20200326_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='fact1',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='fact2',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='fact3',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='fact4',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='fact5',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='fact6',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='fact7',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
