# Generated by Django 2.0.6 on 2020-03-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedestinations', '0007_auto_20200326_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='background',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/bg.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='box1',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/box1.png', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='box2',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/box2.png', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='highs1',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/highs1.png', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='highs2',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/highs2.png', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='highs3',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/highs3.png', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='highs4',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/highs4.png', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nav1',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/nav1.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nav2',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/nav2.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nav3',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/nav3.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='nav4',
            field=models.URLField(blank=True, default='https://s3-eu-central-1.amazonaws.com/othorizon/seedestinations/eg/nav4.jpg', null=True),
        ),
    ]
