# Generated by Django 2.0.6 on 2020-03-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedestinations', '0008_auto_20200326_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='head',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
